apiVersion: v2
name: growthbook
description: Open Source Feature Flags, Experimentation, and Product Analytics
icon: https://avatars.githubusercontent.com/u/65404594
home: https://www.growthbook.io/
sources:
  - https://github.com/growthbook/growthbook/

type: application

# Increment this right before each release
version: "4.3.0"

# Increment this right before each release
appVersion: "4.3.0"

dependencies:
  - name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "^18.0.0"
    condition: mongodb.enabled
  - name: server
    version: "0.0.0"
    alias: frontend
  - name: server
    version: "0.0.0"
    alias: backend

# Increment the version right before each release
annotations:
  artifacthub.io/images: |
    - name: growthbook
      image: growthbook/growthbook:4.3.0
      platforms:
        - linux/amd64
        - linux/arm64