version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  growthbook:
    build: .
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/
      - APP_ORIGIN=https://growthbook-3000-${OKTETO_NAMESPACE}.growthbook.okteto.dev
      - API_HOST=https://growthbook-3100-${OKTETO_NAMESPACE}.growthbook.okteto.dev
      - JWT_SECRET=${JWT_SECRET}
      - IS_CLOUD=true
      - SSO_CONFIG=${SSO_CONFIG}
      - DISABLE_TELEMETRY=debug
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
