parameters:
  - $ref: "../parameters.yaml#/id"
tags:
  - environments
summary: Update an environment
operationId: putEnvironment
x-codeSamples:
  - lang: "cURL"
    source: |
      curl -X PUT https://api.growthbook.io/api/v1/environments/env-id \
         -d '{ "description": "My new environment" }' \
        -u secret_abc123DEF456:
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          description:
            type: string
            description: The description of the new environment
          toggleOnList:
            type: boolean
            description: Show toggle on feature list
          defaultState:
            type: boolean
            description: Default state for new features
          projects:
            type: array
            items:
              type: string
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          required:
            - environment
          properties:
            environment:
              $ref: "../schemas/Environment.yaml"
