datasources:
  warehouse:
    type: postgres
    name: Main Warehouse
    params:
      host: localhost
      port: 5432
      user: root
      password: ${POSTGRES_PW} # use env for secrets
      database: growthbook
    settings:
      queries:
        experimentsQuery: >
          SELECT
            user_id,
            anonymous_id,
            received_at as timestamp,
            experiment_id,
            variation_id,
            context_location_country as country
          FROM
            experiment_viewed]
      experimentDimensions:
        - country
metrics:
  signups:
    type: binomial
    name: Sign Ups
    datasource: warehouse
    sql: SELECT user_id, anonymous_id, received_at as timestamp FROM signups
dimensions:
  subscription_plan:
    name: Subscription Plan
    datasource: warehouse
    sql: SELECT user_id, plan as value from subscriptions
