[tool]
[tool.poetry]
name = "gbstats"
version = "0.6.0"
homepage = "https://github.com/growthbook/growthbook/tree/main/packages/stats"
description = "Stats engine for GrowthBook, the open source feature flagging and A/B testing platform."
authors = ["Jeremy Dorn <jeremy@growthbook.io>"]
readme = "README.md"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
packages = [
    { include = "gbstats" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
pandas = "^1.5.1"
scipy = "^1.9.2"
numpy = "^1.23.4"
nbformat = "^5.8.0"

[tool.poetry.group.dev.dependencies]
certifi = "2022.12.7"
tox = "^3.20.1"
virtualenv = "^20.2.2"
twine = "^3.3.0"
toml = "^0.10.2"
black = "22.3.0"
isort = "5.6.4"
flake8 = "3.8.4"
flake8-docstrings = "^1.6.0"
pytest = "6.2.5"
pytest-cov = "2.10.1"
pandas-stubs = "^2.0.1.230501"
pyright = "^1.1.345"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''