name: Docs
on:
  pull_request:
    paths:
      - "docs/**"
      - "packages/back-end/generated/spec.yaml"
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "packages/back-end/generated/spec.yaml"
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check if main
        run: |
          if [ $REF == 'refs/heads/main' ]
          then
              echo "vercelArgs=--prod" >> $GITHUB_ENV
          else
              echo "vercelArgs=" >> $GITHUB_ENV
          fi
        env:
          REF: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "docs/pnpm-lock.yaml"

      - name: Produce generated files
        run: |
          pnpm install
          cd packages/back-end
          pnpm install
          cd ../../docs
          pnpm install
          pnpm gen

      - name: Deploy to Vercel
        if: ${{ github.repository == 'growthbook/growthbook' }}
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_SCOPE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: ${{ env.vercelArgs }}
          vercel-org-id: ${{ secrets.VERCEL_DOCS_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID}}
          working-directory: ./

  # Linting, type-checking, and tests
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "docs/pnpm-lock.yaml"

      - name: Install dependencies and type-check
        run: |
          cd docs
          pnpm install
          pnpm typecheck
